name: Build & run tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: install
      run: npm install
    - name: lint
      run: npm run lint
      env:
        CI: true
    - name: build
      run: npm run build
      env:
        CI: true
    ## TODO: fix preact test environment
    # - name: test
    #   run: run test
    #   env:
    #     CI: true
